[project]
name = "routstr-proxy"
version = "0.0.1"
description = "Payment proxy for your LLM endpoint using cashu and nostr."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiosqlite>=0.20",
    "cashu>=0.16",
    "fastapi[standard]>=0.115",
    "sqlmodel>=0.0.24",
    "marshmallow<4.0",
]
